### ISSUE TITLE
Integration with Object Detection

### ISSUE THREAD

**Issue by eltonvivot** [telematics-lab/IoD_Sim#4]
Hello,

I'm a Computer Science student and I am doing research in the area of UAV Drones and Computer Vision in 5G networks.

I read the Internet of Drones article and I really enjoyed it! A question that arose was whether it is possible to integrate IoD_Sim with some computer vision system. Maybe, for example, using a drone tracking dataset as input and forwarding it to an object detection system. If it is possible, is there any documentation or guidance on how to do this?

Regards,
Elton.

**Comment by GiovanniGrieco** [comment]
Hi Elton,

nice to meet you and thank you for your interesting question.

It is possible to develop an application that simulates a [camera](https://github.com/telematics-lab/IoD_Sim/blob/b1c0d2fe483b89ad655c11e20ce8c547ae2a4350/drone/model/input-peripheral.h) mounted on the drone that acts as an object tracker. You need to develop your version of the peripheral so that you can feed it with your dataset, then the output may be sent over the simulated network to another simulated remote service. Of course you should also take into account the communication architecture that you want to achieve, which could be a simple [client](https://github.com/telematics-lab/IoD_Sim/blob/b1c0d2fe483b89ad655c11e20ce8c547ae2a4350/drone/model/tcp-stub-client-application.h)-[server](https://github.com/telematics-lab/IoD_Sim/blob/b1c0d2fe483b89ad655c11e20ce8c547ae2a4350/drone/model/tcp-echo-server-application.h) or something more complex.

As a documentation/guidance you can use our [paper](https://arxiv.org/pdf/2203.13710.pdf) and the [example configuration files](https://github.com/telematics-lab/IoD_Sim/tree/v2/drone/config) to understand how IoD Sim, then the [official ns-3 documentation](https://www.nsnam.org/documentation/) can be used to develop your own object tracking models.

Regarding the development environment, I suggest you to use [VSCode](https://code.visualstudio.com/) and make use of the [tasks](https://code.visualstudio.com/Docs/editor/tasks) already [in place](https://github.com/telematics-lab/IoD_Sim/blob/v2/.vscode/tasks.json) to build and run the project.

Best,
Giovanni

**Comment by eltonvivot** [comment]
Hi Giovanni,

I followed your suggestion and I'm using VSCode and tasks to build and run the project. I'm also studying how IoD Sim works. 

Thank you so much for the detailed answer and the suggestions, it helped a lot. :D

Best,
Elton.
